# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YYCacheDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
# Pods for YYCacheDemo
pod 'AFNetworking', '~> 3.2.1'
pod 'SDWebImage'
pod 'YYModel', '~> 1.0.4'
pod 'JSONKit-NoWarning', '~> 1.2'

end
